### ISSUE TITLE
Tweet same link more than once

### ISSUE THREAD

**Issue by amcaw** [peterdalle/twitterbot#4]
Thanks for your script. I'm using it to make tweets from [this RSS feed](https://diplomatie.belgium.be/fr/last-updates/countries/rss). But I can't find how to tweet the same link more than once. If a link has already been published in the RSS feed, it appears as "already posted" in the logs and doesn't generate a new message on my timeline. How can I solve this issue ?

**Comment by peterdalle** [comment]
The script isn't made for that scenario because it would require additional work since every time the RSS feed is read, the script could tweet out the same link over and over again (and Twitter's API typically complain about duplicates).

However, if this is not a problem for you, you could remove [line 110-112](https://github.com/peterdalle/twitterbot/blob/master/twitterbot.py#L110).

So this code:

```py
    feed = feedparser.parse(url)
    if feed:
        for item in feed["items"]:
            link = item["link"]
            if is_in_logfile(link, Settings.posted_urls_output_file):
                print("Already posted:", link)
            else:
                post_tweet(message=compose_message(item))
                write_to_logfile(link, Settings.posted_urls_output_file)
                print("Posted:", link)
    else:
        print("Nothing found in feed", url)
```

Will look like this:

```py
    feed = feedparser.parse(url)
    if feed:
        for item in feed["items"]:
            link = item["link"]
            post_tweet(message=compose_message(item))
            write_to_logfile(link, Settings.posted_urls_output_file)
            print("Posted:", link)
    else:
        print("Nothing found in feed", url)
```

Note that the `if`-statement that checks if the link is in the logfile is gone.
