### ISSUE TITLE
Posting title or description with image 

### ISSUE THREAD

**Issue by cmutts** [peterdalle/twitterbot#7]
Hi, is it possible to post the tweet with an image preview on Twitter? It only posts the tweet and a link to the image.

**Comment by peterdalle** [comment]
Twitter is responsible for providing image previews by extracting the [`twitter:image`](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image) from the target URL. It's not something that this application can control.

Uploading images to the tweet, however, will not be supported by this application because it's not what it's intended for.
